[package]
name = "tasm-lib"
version = "0.1.0"
edition = "2021"
authors = ["Triton Software AG"]

description = "Code snippets for Triton VM assembly with tests and statistics."
readme = "README.md"
license = "Apache-2.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
anyhow = "1"
triton-vm = "0.31.1"
# triton-vm = {path = "../triton-vm/triton-vm"}
triton-opcodes = "0.31.0"
# triton-opcodes = {path = "../triton-vm/triton-opcodes" }
twenty-first = "0.30.0"
rand = "0"
itertools = "0"
num = "0"
num-traits = "0"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
