[package]
name = "tasm-snippets"
version = "0.1.0"
edition = "2021"
authors = ["Triton Software AG"]

description = "Code snippets for Triton VM assembly with tests and statistics."
readme = "../README.md"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
triton-vm = "0.14"
triton-opcodes = "0.14"
twenty-first = "0.14.1"
rand = "0.8.5"
itertools = "0.10.5"
num = "0.4.0"
num-traits = "0"
rayon = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
