[package]
name = "tasm-lib"
description = """
Code snippets for Triton VM assembly with tests and statistics.
"""

keywords = ["Triton-VM", "zero-knowledge", "STARK", "virtual-machine", "recursive"]
categories = ["cryptography"]

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
readme.workspace = true

[dev-dependencies]
color-eyre = "0.6"
proptest = "1.5"
proptest-arbitrary-interop = "0.1"
test-strategy = "0.4"
rayon = "1"

[dependencies]
const_format = "0.2"
arbitrary = { version = "1", features = ["derive"] }
anyhow = "1"
tasm-object-derive.workspace = true
ndarray = { version = "0.16" }
hex = "^0.4.3"
itertools = "0"
num = "0"
num-traits = "0"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.26", features = ["derive"] }
triton-vm = { version = "0.43.0", default-features = false }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
