[package]
name = "tasm-lib"
version = "0.2.1"
edition = "2021"
authors = ["Triton Software AG"]

description = "Code snippets for Triton VM assembly with tests and statistics."
readme = "../README.md"
license = "Apache-2.0"

[dev-dependencies]
color-eyre = "0.6"
proptest = "1.4"
proptest-arbitrary-interop = "0.1"
test-strategy = "0.3"
rayon = "1"

[dependencies]
const_format = "0.2"
arbitrary = { version = "1", features = ["derive"] }
anyhow = "1"
derive_tasm_object = { path = "../derive_tasm_object" }
ndarray = { version = "0.15" }
hex = "^0.4.3"
itertools = "0"
num = "0"
num-traits = "0"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.26", features = ["derive"] }
triton-vm = { version = "0.42.0-alpha.5", default-features = false }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
