[package]
name = "tasm-lib"
version = "0.2.1"
edition = "2021"
authors = ["Triton Software AG"]

description = "Code snippets for Triton VM assembly with tests and statistics."
readme = "README.md"
license = "Apache-2.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
anyhow = "1"
derive_tasm_object = { path = "../derive_tasm_object" }
hex = "^0.4.3"
itertools = "0"
num = "0"
num-traits = "0"
rand = "0.8.5"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
triton-vm = "0.34.1"
twenty-first = "0.34"
