[package]
name = "derive_tasm_object"
version = "0.1.0"
edition = "2021"
description = "Derive macro for TasmObject"

[dependencies]
quote = "1.0"
syn = { version = "^2", features = ["full", "derive"] }
proc-macro2 = { version = "1" }

[lib]
proc-macro = true
